import { StandardTableView, TabWidget, ListView, HorizontalBox, CheckBox, ComboBox} from "std-widgets.slint";
import { Sources, UiTransactionSource } from "./sources.slint";
import { Transactions, UiTransaction } from "./transactions.slint";

import { CapitalGains } from "./capital-gains.slint";

// Unused by Slint for now, but might be a better way of exposing data to UI
export struct UiCapitalGain {
    currency: string,
    bought: string,
    sold: string,
    quantity: float,
    cost: float,
    proceeds: float,
    gain_or_loss: float,
    long_term: bool,
}

enum Page {
    sources,
    transactions,
    capital-gains,
}

component Badge inherits VerticalLayout {
    in-out property text <=> txt.text;
    alignment: center;

    Rectangle {
        vertical-stretch: 0;
        horizontal-stretch: 0;

        background: #434343;
        border-radius: self.height / 2;
        height: txt.preferred-height + 2px;
        width: txt.preferred-width + 12px;

        txt := Text {
            text: 123;
            color: white;
            font-size: 10px;
        }
    }
}

component PageButton inherits Rectangle {
    in-out property text <=> txt.text;
    in property <bool> active;

    callback pressed;

    border-radius: root.height / 4;
    background: root.active ? #456 : transparent;
    height: layout.preferred-height * 1.33;
    width: layout.preferred-width + 20px;

    layout := HorizontalLayout {
        spacing: 10px;
        alignment: center;
        txt := Text {
            font-size: 14px;
            vertical-alignment: center;
        }

        @children
    }
    touch := TouchArea {
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                root.pressed();
            }
        }
    }
}

export component AppWindow inherits Window {
    in property <[UiTransactionSource]> sources;
    in property <[string]> source_types;
    in property <[UiTransaction]> transactions;
    in property <[[StandardListViewItem]]> gain-entries;

    callback open-transaction(string);

    property <Page> active-page: Page.sources;

    title: "Crypto Tax Tool";

    min-width: 512px;
    min-height: 160px;
    preferred-width: 1200px;
    preferred-height: 640px;

    VerticalLayout {
        HorizontalBox {
            alignment: center;

            PageButton {
                text: "Sources";
                active: root.active-page == Page.sources;
                pressed => { root.active-page = Page.sources; }

                Badge {
                    text: root.sources.length;
                }
            }
            PageButton {
                text: "Transactions";
                active: root.active-page == Page.transactions;
                pressed => { root.active-page = Page.transactions; }

                Badge {
                    text: root.transactions.length;
                }
            }
            PageButton {
                text: "Capital Gains";
                active: root.active-page == Page.capital-gains;
                pressed => { root.active-page = Page.capital-gains; }

                Badge {
                    text: root.gain-entries.length;
                }
            }
        }

        if (active-page == Page.sources): Sources {
            sources: root.sources;
        }

        if (active-page == Page.transactions): Transactions {
            transactions: root.transactions;
            open-transaction(s) => { root.open-transaction(s); }
        }

        if (active-page == Page.capital-gains): CapitalGains {
            gain-entries: root.gain-entries;
        }
    }
}
