import { HorizontalBox, CheckBox, ComboBox} from "std-widgets.slint";
import { Portfolio } from "./portfolio.slint";
import { Sources } from "./sources.slint";
import { Transactions } from "./transactions.slint";
import { Reports } from "./reports.slint";
import { Badge } from "./common.slint";
import { Facade } from "./global.slint";
import { UiCapitalGain } from "./structs.slint";

export { UiCapitalGain, Facade }

enum Page {
    portfolio,
    sources,
    transactions,
    reports,
}

component PageButton inherits Rectangle {
    in property <string> text <=> txt.text;
    in property <bool> active;

    callback pressed;

    border-radius: self.height / 4;
    border-color: (touch.has-hover || root.active) ? #456 : #3e3e3e;
    border-width: 1px;
    background: root.active ? #456 : transparent;
    height: layout.preferred-height * 1.33;
    width: layout.preferred-width + 20px;

    layout := HorizontalLayout {
        spacing: 10px;
        alignment: center;
        txt := Text {
            font-size: 14px;
            vertical-alignment: center;
        }

        @children
    }
    touch := TouchArea {
        pointer-event(event) => {
            if (event.kind == PointerEventKind.down) {
                root.pressed();
            }
        }
    }
}

export component AppWindow inherits Window {
    property <Page> active-page: Page.portfolio;

    title: "Crypto Tax Tool";

    min-width: 512px;
    min-height: 160px;
    preferred-width: 1200px;
    preferred-height: 640px;

    VerticalLayout {
        HorizontalBox {
            alignment: center;

            PageButton {
                text: "Portfolio";
                active: root.active-page == Page.portfolio;
                pressed => { root.active-page = Page.portfolio; }
            }
            PageButton {
                text: "Sources";
                active: root.active-page == Page.sources;
                pressed => { root.active-page = Page.sources; }

                Badge {
                    text: Facade.sources.length;
                }
            }
            PageButton {
                text: "Transactions";
                active: root.active-page == Page.transactions;
                pressed => { root.active-page = Page.transactions; }

                Badge {
                    text: Facade.transactions.length;
                }
            }
            PageButton {
                text: "Reports";
                active: root.active-page == Page.reports;
                pressed => { root.active-page = Page.reports; }

                Badge {
                    text: Facade.reports.length;
                }
            }
        }

        Rectangle {
            portfolio-page := Portfolio {
                visible: active-page == Page.portfolio;
            }

            sources-page := Sources {
                visible: active-page == Page.sources;
                source-transactions-clicked(index) => {
                    Facade.set-source-filter(index);
                    root.active-page = Page.transactions;
                }
            }

            transactions-page := Transactions {
                visible: active-page == Page.transactions;
            }

            reports-page := Reports {
                visible: active-page == Page.reports;
            }
        }
    }
}
