import { StandardTableView } from "std-widgets.slint";

export component CapitalGains inherits StandardTableView {
    in property <[[StandardListViewItem]]> gain-entries;

    columns: [
        { title: "Currency" },
        { title: "Bought" },
        { title: "Sold" },
        { title: "Quantity" },
        { title: "Cost" },
        { title: "Proceeds" },
        { title: "Gain or Loss" },
        { title: "Long Term" },
    ];
    rows: gain_entries;
}
