export component Badge inherits VerticalLayout {
    in-out property text <=> txt.text;
    alignment: center;

    Rectangle {
        vertical-stretch: 0;
        horizontal-stretch: 0;

        background: #434343;
        border-radius: self.height / 2;
        height: txt.preferred-height + 2px;
        width: txt.preferred-width + 12px;

        txt := Text {
            text: 123;
            color: white;
            font-size: 10px;
        }
    }
}

export component CurrencyIcon inherits Image {
    in property <int> cmc-id;

    width: 14px;
    source: cmc-id == 1 ? @image-url("icons/coins/1.png"):
            cmc-id == 2 ? @image-url("icons/coins/2.png") :
            cmc-id == 5 ? @image-url("icons/coins/5.png") :
            cmc-id == 8 ? @image-url("icons/coins/8.png") :
            cmc-id == 52 ? @image-url("icons/coins/52.png") :
            cmc-id == 131 ? @image-url("icons/coins/131.png") :
            cmc-id == 328 ? @image-url("icons/coins/328.png") :
            cmc-id == 512 ? @image-url("icons/coins/512.png") :
            cmc-id == 873 ? @image-url("icons/coins/873.png") :
            cmc-id == 1027 ? @image-url("icons/coins/1027.png") :
            cmc-id == 1437 ? @image-url("icons/coins/1437.png") :
            cmc-id == 1720 ? @image-url("icons/coins/1720.png") :
            cmc-id == 1831 ? @image-url("icons/coins/1831.png") :
            cmc-id == 1839 ? @image-url("icons/coins/1839.png") :
            cmc-id == 1966 ? @image-url("icons/coins/1966.png") :
            @image-url("");
}

export component Cell inherits HorizontalLayout {
    horizontal-stretch: 1;
    preferred-width: 0;
    min-width: 0;
    spacing: 5px;
}

export component ElidingText inherits Text {
    overflow: elide;
    vertical-alignment: center;
}

export component TextCell inherits ElidingText {
    horizontal-stretch: 1;
    preferred-width: 0;
    min-width: 0;
}

export component MonoTextCell inherits TextCell {
    font-family: "DejaVu Sans Mono";
    horizontal-alignment: right;
}

export component TableHeader inherits VerticalLayout {
    spacing: 2px;
    vertical-stretch: 0;
    // width: view.visible-width;   // what we want, but causes binding loop

    HorizontalLayout {
        padding-left: 7px;
        padding-right: 15px;
        padding-top: 2px;
        padding-bottom: 2px;
        spacing: 2px;

        @children
    }

    Rectangle {
        height: 1px;
        background: white;
        opacity: 0.25;
    }
}

export component HeaderCell inherits ElidingText {
    horizontal-stretch: 1;
    preferred-width: 0;
    min-width: 0;
    opacity: 0.8;
    font-size: 10px;
}

export component DateTimeCell inherits HorizontalLayout {
    in property <string> date <=> date-text.text;
    in property <string> time <=> time-text.text;

    alignment: start;
    spacing: 6px;
    padding-right: 15px;

    date-text := ElidingText {
        min-width: self.preferred-width;
        text: "2013-10-30";
    }
    time-text := ElidingText {
        opacity: 0.5;
        font-size: 10px;
        min-width: self.preferred-width;
        text: "12:34:56";
    }
}
