import {
    UiBalanceForCurrency,
    UiBalanceForSource,
    UiCapitalGain,
    UiPortfolio,
    UiTaxReport,
    UiTransaction,
    UiTransactionSource
} from "structs.slint";
import { TestData } from "test-data.slint";

export global Facade {
    // MODELS

    in-out property <[UiTransactionSource]> sources: TestData.sources;
    in-out property <[string]> source-types;
    in-out property <[UiTransaction]> transactions: TestData.transactions;
    in-out property <[StandardListViewItem]> report-years: TestData.report-years;
    in-out property <[UiTaxReport]> reports: TestData.reports;
    in-out property <UiPortfolio> portfolio: TestData.portfolio;

    out property <int> source-filter: -1;
    out property <string> currency-filter: "";

    // ACTIONS

    // params: (blockchain, tx_hash)
    callback open-transaction(string, string);

    // params: (source_index, enabled)
    callback set-source-enabled(int, bool);

    // params: (source_index)
    callback sync-source(int);

    // params: (report_index)
    callback export-summary(int);
    callback export-capital-gains(int);

    callback export-transactions-csv;
    callback export-transactions-json;

    callback transaction-filter-changed;

    // DATA REQUESTS

    // params: (currency)
    pure callback balances-for-currency(string) -> [UiBalanceForCurrency];

    // params: (source_index)
    pure callback balances-for-source(int) -> [UiBalanceForSource];

    // FUNCTIONS

    function set-source-filter(source-index: int) {
        if (source-filter != source-index || currency-filter != "") {
            source-filter = source-index;
            currency-filter = "";
            transaction-filter-changed();
        }
    }

    function set-currency-filter(currency: string) {
        if (currency-filter != currency || source-filter != -1) {
            currency-filter = currency;
            source-filter = -1;
            transaction-filter-changed();
        }
    }
}
