import {
    UiCapitalGain,
    UiPortfolio,
    UiTaxReport,
    UiTransaction,
    UiTransactionSource
} from "./structs.slint";
import { TestData } from "./test-data.slint";

export global Facade {
    // MODELS

    in-out property <[UiTransactionSource]> sources: TestData.sources;
    in-out property <[string]> source-types;
    in-out property <[UiTransaction]> transactions: TestData.transactions;
    in-out property <[StandardListViewItem]> report-years: TestData.report-years;
    in-out property <[UiTaxReport]> reports: TestData.reports;
    in-out property <UiPortfolio> portfolio: TestData.portfolio;

    out property <int> source-filter: -1;

    // ACTIONS

    // params: (blockchain, tx_hash)
    callback open-transaction(string, string);

    // params: (source_index, enabled)
    callback set-source-enabled(int, bool);

    // params: (report_index)
    callback export-summary(int);
    callback export-capital-gains(int);

    callback transaction-filter-changed;

    // FUNCTIONS

    function set-source-filter(source-index: int) {
        if (source-filter != source-index) {
            source-filter = source-index;
            transaction-filter-changed();
        }
    }
}
