import { ListView, HorizontalBox, CheckBox, ComboBox, Button } from "std-widgets.slint";
import { Badge, ElidingText } from "common.slint";
import { Facade } from "global.slint";
import { UiTransactionSource } from "structs.slint";

export component Sources inherits ListView {
    in property <[UiTransactionSource]> sources: Facade.sources;

    callback source-transactions-clicked(int);

    for source[index] in sources: HorizontalBox {
        CheckBox {
            checked: source.enabled;
            text: source.name;

            toggled => {
                source.enabled = self.checked;
                Facade.set-source-enabled(index, self.checked);
            }
        }
        ElidingText {
            text: source.path;
        }
        Rectangle { width: 1px; }
        Badge {
            text: "\{source.transaction-count} transactions";
            clicked => { root.source-transactions-clicked(index); }
        }
        Rectangle {}
        ComboBox {
            model: Facade.source-types;
            horizontal-stretch: 0;
            current-value: source.source_type;
            enabled: false;
        }
        Button {
            text: "Sync";
            enabled: source.can-sync;
            clicked => { Facade.sync-source(index); }
        }
    }
}
