import { ListView, HorizontalBox, CheckBox, ComboBox } from "std-widgets.slint";
import { Badge } from "./common.slint";
import { UiTransactionSource } from "./structs.slint";

export component Sources inherits ListView {
    in property <[UiTransactionSource]> sources;
    in property <[string]> source_types;

    for source in sources: HorizontalBox {
        CheckBox {
            checked: true;
            text: source.name;
            enabled: false;
        }
        Text {
            text: source.path;
            vertical-alignment: center;
        }
        Rectangle { width: 1px; }
        Badge {
            text: "\{source.transaction-count} transactions";
            opacity: 0.8;
        }
        Rectangle {}
        ComboBox {
            model: source_types;
            horizontal-stretch: 0;
            current-value: source.source_type;
            enabled: false;
        }
    }
}
