import { VerticalBox, StandardTableView, TabWidget, ListView } from "std-widgets.slint";

export enum UiTransactionType {
    buy,
    sell,
    deposit,
    withdrawal,
    fee,
    receive,
    send,
    chain-split,
    expense,
    income,
    airdrop,
    spam,
}

export struct UiTransaction {
    date: string,
    time: string,
    tx_type: UiTransactionType,
    received: string,
    sent: string,
    fee: string,
    gain: float,
    description: string,
    tx_hash: string,
}

// Unused by Slint for now, but might be a better way of exposing data to UI
export struct UiCapitalGain {
    currency: string,
    bought: string,
    sold: string,
    quantity: float,
    cost: float,
    proceeds: float,
    gain_or_loss: float,
    long_term: bool,
}

component ElidingText inherits Text {
    width: 100%;
    height: 100%;
    overflow: elide;
    vertical-alignment: center;
}

component Cell inherits Rectangle {
    horizontal-stretch: 1;
    preferred-width: 0;
    min-width: 0;
}

component TransactionDisplay inherits Rectangle {
    in property <UiTransaction> tx : {
        date: "2013-11-01",
        time: "12:34:56",
        tx_type: UiTransactionType.send,
        received: "1 BTC",
        sent: "300 EUR",
        fee: "1 EUR",
        gain: 0.0,
        description: "Foo bar baz",
        tx_hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
    };

    in property <bool> even;

    background: even ? #ffffff06 : transparent;

    HorizontalLayout {
        padding-top: 2px;
        padding-bottom: 2px;
        Cell {
            ElidingText {
                text: tx.tx-type == UiTransactionType.buy ? "Buy" :
                    tx.tx-type == UiTransactionType.sell ? "Sell" :
                    tx.tx-type == UiTransactionType.deposit ? "Deposit" :
                    tx.tx-type == UiTransactionType.withdrawal ? "Withdrawal" :
                    tx.tx-type == UiTransactionType.fee ? "Fee" :
                    tx.tx-type == UiTransactionType.receive ? "Receive" :
                    tx.tx-type == UiTransactionType.send ? "Send" :
                    tx.tx-type == UiTransactionType.chain-split ? "Chain Split" :
                    tx.tx-type == UiTransactionType.expense ? "Expense" :
                    tx.tx-type == UiTransactionType.income ? "Income" :
                    tx.tx-type == UiTransactionType.airdrop ? "Airdrop" :
                    tx.tx-type == UiTransactionType.spam ? "Spam" :
                    "Unknown";
            }
        }
        HorizontalLayout {
            alignment: start;
            spacing: 6px;
            padding-right: 12px;
            Text {
                text: tx.date;
                overflow: elide;
                min-width: self.preferred-width;
            }
            Text {
                text: tx.time;
                opacity: 0.5;
                overflow: elide;
                min-width: self.preferred-width;
            }
        }
        Cell {
            ElidingText {
                text: tx.sent == "" ? "" : "–\{tx.sent}";
            }
        }
        Cell {
            ElidingText {
                text: tx.received == "" ? "" : "+\{tx.received}";
            }
        }
        Cell {
            ElidingText {
                text: tx.gain == 0 ? "–" : tx.gain;
                color: tx.gain < 0 ? #ff0000 : tx.gain > 0 ? #00ff00 : transparent;
            }
        }
    }
}

export component AppWindow inherits Window {
    in property <[UiTransaction]> transactions;
    in property <[[StandardListViewItem]]> gain_entries;

    title: "Crypto Tax Tool";

    min-width: 512px;
    min-height: 160px;
    preferred-width: 1200px;
    preferred-height: 640px;

    TabWidget {
        Tab {
            title: "Transactions (\{transactions.length})";

            transactions-view := ListView {
                for tx[index] in transactions: TransactionDisplay {
                    even: mod(index, 2) == 0;
                    tx: tx;
                }
            }
        }
        Tab {
            title: "Capital Gains (\{gain_entries.length})";

            StandardTableView {
                width: 100%;
                height: 100%;

                columns: [
                    { title: "Currency" },
                    { title: "Bought" },
                    { title: "Sold" },
                    { title: "Quantity" },
                    { title: "Cost" },
                    { title: "Proceeds" },
                    { title: "Gain or Loss" },
                    { title: "Long Term" },
                ];
                rows: gain_entries;
            }
        }
    }
}
