name: Rust

on:
  push:
    paths-ignore:
    - 'docs/**'
    - '**.md'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: sudo apt update && sudo apt install libfontconfig-dev
    - run: cargo build --verbose --release
    - run: cargo install cargo-packager --locked
    - run: cargo packager --release
    - uses: actions/upload-artifact@v4
      with:
        name: Raccoin.AppImage
        path: target/release/raccoin_*.AppImage
    - uses: actions/upload-artifact@v4
      with:
        name: Raccoin.deb
        path: target/release/raccoin_*.deb

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo build --verbose --release
    - run: cargo install cargo-packager --locked
    - run: cargo packager --release
    - uses: actions/upload-artifact@v4
      with:
        name: Raccoin-setup.exe
        path: target/release/raccoin_*-setup.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install targets
      run: |
        rustup target add x86_64-apple-darwin
        rustup target add aarch64-apple-darwin
    - name: Build Intel binary
      run: cargo build --verbose --release --target x86_64-apple-darwin
    - name: Build ARM64 binary
      run: cargo build --verbose --release --target aarch64-apple-darwin
    - name: Create universal binary
      run: |
        mkdir -p target/release
        lipo -create \
          target/x86_64-apple-darwin/release/raccoin \
          target/aarch64-apple-darwin/release/raccoin \
          -output target/release/raccoin
    - name: Create .icns file
      run: iconutil -c icns raccoin_ui/ui/icons/Raccoin.iconset
    - run: cargo install cargo-packager --locked
    - run: cargo packager --release
    - run: ditto -c -k --sequesterRsrc --keepParent target/release/Raccoin.app Raccoin.app.zip
    - uses: actions/upload-artifact@v4
      with:
        name: Raccoin.app
        path: Raccoin.app.zip
    - uses: actions/upload-artifact@v4
      with:
        name: Raccoin.dmg
        path: target/release/Raccoin_*.dmg
